2022-01-01 12:51:09,928 INFO: Initialized curve data.
2022-01-01 12:51:09,930 INFO: Setting up initial twist data...
2022-01-01 12:51:11,037 INFO: Twist setup complete.
2022-01-01 12:51:11,037 INFO: Searching for rational points on each twist...
2022-01-01 12:51:12,735 INFO: Finished searching for rational points on each twist.
2022-01-01 12:51:12,735 INFO: Testing local solvability of twists...
2022-01-01 13:00:59,748 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 458, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 243, in twists_locally_solvable
    ls2 = magma.function_call("is_genus5_locally_solvable_at_2", Z)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 7560.4MB, failed memory request: 1496.9MB
System Error: User memory limit has been reached
2022-01-03 13:14:58,000 INFO: Obsolete "loc_solv_error" keys removed.
2022-01-10 22:42:06,565 INFO: Loaded curve data from file.
2022-01-10 22:42:06,566 INFO: Reducing MW generators...
2022-01-10 22:42:06,566 INFO: Finished reducing MW generators.
2022-01-10 22:42:06,568 INFO: Skipped Chabauty because no base point (delta = ['-16', '4', '7', '-13', '0', '16'])
2022-01-10 22:42:06,568 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '-4', '0', '-4', '-4'], g = [-1, 1])
2022-01-10 22:42:06,568 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '-4', '0', '-4', '-4'], g = [4, 3, 1, 4, 4])
2022-01-10 22:42:06,568 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '0', '2', '-3', '0', '4'], g = [-1, 1])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '0', '2', '-3', '0', '4'], g = [4, 3, 1, 4, 4])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['16', '0', '-4', '12', '4', '-12'], g = [-1, 1])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['16', '0', '-4', '12', '4', '-12'], g = [4, 3, 1, 4, 4])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [-1, 1])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [4, 3, 1, 4, 4])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because no base point (delta = ['-16', '-4', '1', '-14', '-7', '8'])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because no base point (delta = ['64', '-8', '-26', '51', '8', '-57'])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['4', '0', '-1', '3', '0', '-4'], g = [-1, 1])
2022-01-10 22:42:06,569 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['4', '0', '-1', '3', '0', '-4'], g = [4, 3, 1, 4, 4])
2022-01-10 22:42:06,642 INFO: Tasks complete. Recording data and exiting.
2022-02-12 17:39:47,786 INFO: Loaded curve data from file.
2022-02-12 17:39:47,787 INFO: Tasks complete. Recording data and exiting.
